### ISSUE TITLE
Add coverage test

### ISSUE THREAD

**Issue by ericelliott** [ericelliott/prod-module-boilerplate#1]
Figure out how to get Istanbul or similar working with Babel.

**Comment by nkbt** [comment]
Check my research, might be helpful https://github.com/nkbt/esnext-quickstart/issues/4
So after all coverage is working well, except there are still some minor issue with the way es6 classes are transpiled.

**Comment by ericelliott** [comment]
Thanks! I was planning to try that `$ babel --auxiliary-comment "istanbul ignore next"` hack. Nice job capturing that documentation. =)

**Comment by ericelliott** [comment]
I'm adding you as a contributor to this repo. Feel free to suggest changes or submit PRs for review if you like. =)

**Comment by nkbt** [comment]
Added some scripts, basic test and istanbul.

Coverage looks like this:
![20150615-233036](https://cloud.githubusercontent.com/assets/175264/8161017/44d53be4-13b7-11e5-9ef6-c9b187ca5463.png)

To test if auxiliary-comment works, added `import test from 'tape';` to `index.js`. Works fine. Extra text does not affect coverage.

![20150615-233008](https://cloud.githubusercontent.com/assets/175264/8161056/7afd6c78-13b7-11e5-9e80-f832c83fcf6a.png)

I've also added branch `coverage` with bunch of extras for testing and coverage (karma, webpack, watch-mode) but then decided to keep it lean for the moment. Check it anyway.

**Comment by revolunet** [comment]
also check this project : https://github.com/douglasduteil/isparta :  code coverage tool for ES6 using babel.

**Comment by nkbt** [comment]
I tried it several months ago with not much luck. Need to check again in case of something good happened.
Btw coverage is working and in master now. Just does not look too pretty.

**Comment by nkbt** [comment]
My ideal solution would be - take some super-modern-nightly-build browser with full support of modules, classes and all new shiny es6/7 features and run coverage on that. But there is no such browser yet.

**Comment by nkbt** [comment]
Just found a perfect solution https://github.com/nkbt/esnext-quickstart/issues/4#issuecomment-112242629 with https://github.com/deepsweet/isparta-loader

![20150616-095442](https://cloud.githubusercontent.com/assets/175264/8173229/be46f4c6-140d-11e5-94ed-0fb1351daf41.png)

Will update the code tonight

**Comment by ericelliott** [comment]
Cool.. Please use the pull request mechanism when you contribute code changes.

**Comment by nkbt** [comment]
@ericelliott yes, will do.

**Comment by ericelliott** [comment]
:+1: 

Thanks! =)

**Comment by ericelliott** [comment]
Thanks a lot for taking the time to figure out how to get the coverage report looking like it should! I really appreciate that effort.

I just have a few concerns with the PR... looking forward to your response so we can get this great work merged. =)

**Comment by nkbt** [comment]
I will make changes accordingly. Communication might take some time due to different timezones (I am in Sydney, GMT+10)

**Comment by ericelliott** [comment]
Very cool. =)

**Comment by ericelliott** [comment]
:tada: :fire: :clap:
