### ISSUE TITLE
Mechanism to automate updates of compiled releases

### ISSUE THREAD

**Issue by ericelliott** [ericelliott/prod-module-boilerplate#18]
We need to supply a mechanism to automate updates to services like cdnjs (for modules like [stampit](https://github.com/stampit-org/stampit) & [cuid](https://github.com/ericelliott/cuid)).

## Possible solution - check in build

Right now the build directory isn't being checked in, primarily because it causes noise in diffs. We can fix that.

### Ignore build directory in diffs

You can [ignore build files in diffs](https://github.com/gitlabhq/gitlabhq/issues/6916#issuecomment-62520577).

Create a `.gitattributes` file in the repo root:

```
build    -diff
```

**Comment by nkbt** [comment]
.gitattributes is cool!

But why would you check in build artifacts into the repo?

In case of npm module you can have prepublish script and .npmignore

In case of static examples, it is ok to check in built statics and then this one is helpful.

**Comment by nkbt** [comment]
As an example from one of my modules

### npmignore
```
coverage/
example/
src/
test/
.coveralls.yml
.eslintrc
.gitignore
.npmignore
circle.yml
karma.conf.js
webpack.config.js
```
### npm scripts
```
"prepublish": "npm run build",
"build": "npm run build:clean && npm run build:lib && npm run build:example",
"build:clean": "rm -rf lib example",
"build:lib": "babel -sd lib src",
"build:example": "webpack",
```
### gitignore
```
lib
/example/
.coveralls.yml
```

This produces clean npm module without any extras. Git repo also does not have anything in there.

Exapmles dir is excluded from gitignore on `gh-pages` branch.

**Comment by troutowicz** [comment]
I don't see a reason to be tracking build artifacts ever. A project's `prepublish` script gets ran during a local `npm install`, which should be building the artifacts.

**Comment by ericelliott** [comment]
OK. =)

**Comment by nkbt** [comment]
It should be achievable with TavisCI or CircleCI. I can figure out how to make it with CI rather then source code.

**Comment by ericelliott** [comment]
That would be great! =)

**Comment by nkbt** [comment]
Right. I was going to do the same for my modules anyway.

**Comment by ericelliott** [comment]
:+1:

**Comment by nkbt** [comment]
I did some investigation and it seems pretty straightforward. But requires a tiny one-time manual work for each lib. It will be auto-updated on cdnjs with each new npm version published

1. Update `package.json` with additional section
```json
  "autoupdate": {
    "source": "git",
    "target": "git://github.com/my-lib/mylib.git",
    "basePath": "build/",
    "files": [
      "my-lib.js",
      "my-lib.min.js"
    ]
  }
```
2. If library was never published on cdnjs before, you need to add it to their repo. Here is a short guide how to do that with [cdnjs-importer](https://github.com/IonicaBizau/cdnjs-importer)
```bash
cd ~
git clone git@github.com:cdnjs/cdnjs.git
npm install -g cdnjs-importer
cdnjs-importer -c ~/cdnjs git://github.com/my-lib/mylib.git
```

That's it.

I reckon we could automate it even further, but not convinced that we should. This is one-time operation.

The only thing we do not have yet - js minifier. I will create a ticket for that.

**Comment by nkbt** [comment]
One more thing. If we don't want to have built files in git, that is okay, since cdnjs works fine with npm-only. `package.json` config should be different in this case:

```json
  "npmName": "my-lib",
  "npmFileMap": [{
    "basePath": "/dist/",
    "files": [
      "my-lib.js",
      "my-lib.min.js"
    ]
  }],
```

**Comment by ericelliott** [comment]
Looks great!
