### ISSUE TITLE
More webpack loaders?

### ISSUE THREAD

**Issue by nkbt** [ericelliott/prod-module-boilerplate#21]
Do we need some common and useful ones? For json, css, images? So you can import css in the module? 

Webpack dev server with static html generation?

Initially I put them, but then decided to keep config without any unused extras.

**Comment by ericelliott** [comment]
Let's leave out any unused extras. Those features should probably opt-in with a boilerplate like this.

**Comment by nkbt** [comment]
Yes, cool.
