### ISSUE TITLE
Add webpack to doc

### ISSUE THREAD

**Issue by ericelliott** [ericelliott/prod-module-boilerplate#23]
The animated screenshot you used in [the PR](https://github.com/ericelliott/prod-module-boilerplate/pull/20#issue-90357059) was cool. Should we  put that in the doc?

![webpack](https://cloud.githubusercontent.com/assets/175264/8304834/d66f7944-19ec-11e5-9feb-9f66caa5c593.gif)

**Comment by nkbt** [comment]
Yeah, vis is always good. By the way I am using [licecap](http://www.cockos.com/licecap/) and it is just great.
