### ISSUE TITLE
Switch to blue-tape

### ISSUE THREAD

**Issue by ericelliott** [ericelliott/prod-module-boilerplate#32]
[blue-tape](https://github.com/spion/blue-tape) Is a tape wrapper with promise support so you don't have to use `.plan()` or `.end()`.

**Comment by ericelliott** [comment]
@nkbt Shouldn't take long. =)

**Comment by ericelliott** [comment]
Could you knock this out?  =)

**Comment by nkbt** [comment]
Yep. Will do.
Was off a little bit with my partial routing solution library - `in-flux`.
It is mostly completed so will do more stuff on a side now again!



-- 
Sincerely yours, Nikita Butenko
Google Talk: nik@butenko.me
Skype: nikita.butenko
Mobile: +61 450 264 801

**Comment by ericelliott** [comment]
Cool. =)

**Comment by ericelliott** [comment]
:+1:
